#!/usr/bin/env bash
# script that transfers a file from our client to a server
if (( $# < 4 ))
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
host="$3@$2"
scp -i "$4" -J "$host" "$1" ~/
