#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect some requirements
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mv /var/www/html/index.nginx-debian.html /var/www/html/save_index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
