#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect some requirements
sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx start
