#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect some requirements
ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
