#!/usr/bin/env bash
# Configure nginx web server with custom response header

INDEX_COPY="Holberton School for the win!"
ERROR_COPY="Ceci n'est pas une page - 404"

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Set custom index and error pages
echo "$INDEX_COPY" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "$ERROR_COPY" | sudo tee /var/www/html/custom_404.html > /dev/null

# Create a custom-header.conf file for Nginx configuration
sudo tee /etc/nginx/conf.d/custom-header.conf > /dev/null <<EOF
server {
    location / {
        add_header X-Served-By \$host;
    }
}
EOF

sudo service nginx start
