#!/usr/bin/env bash
# Configure nginx web server with custom response header

INDEX_COPY="Holberton School for the win!"
ERROR_COPY="Ceci n'est pas une page - 404"

sudo apt-get -y update
sudo apt-get -y install nginx

echo "$INDEX_COPY" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "$ERROR_COPY" | sudo tee /var/www/html/custom_404.html > /dev/null

# config redirection
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo printf "%s" "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	add_header X-Served-By $HOSTNAME;

	location = /redirect_me/ {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

}" > /etc/nginx/sites-available/default

sudo service nginx start
