#!/usr/bin/env bash
# Install and configure HAProxy load balancer

# Update package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy service
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend load_balancer
    bind 0.0.0.0:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 52.87.220.246:80 check
    server web-02 54.162.92.7:80 check
EOF

# Start HAProxy service
sudo service haproxy start
