#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy
    maxconn 2000
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    option forwardfor
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 264802-web-01:80 check
    server web-02 264802-web-02:80 check
EOF

# Add hostname entries to /etc/hosts
echo "127.0.0.1 264802-web-01" | sudo tee -a /etc/hosts > /dev/null
echo "127.0.0.1 264802-web-02" | sudo tee -a /etc/hosts > /dev/null

# Restart HAProxy
sudo service haproxy restart

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
