#!/usr/bin/env bash
# script with the minimum number of commands to automate my fix.
apt-get update
apt-get install -y nginx

echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default

systemctl restart nginx

systemctl status nginx
