#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.
echo "$$" > /var/run/myscript.pid
while((1))
do
  echo "To infinity and beyond"
  trap '(echo "I hate the kill command"; rm /var/run/myscript.pid)' SIGTERM
  trap '(echo "Y U no love me?!"; rm /var/run/myscript.pid)' SIGINT
done
