#!/usr/bin/env bash
#This script displays Best School 10 times,
#but for the 9th iteration, displays "Best School"
#and then "Hi" on a new line.
for((i = 1; i <= 10; i++))
do
  echo "Best School"
  if [ $i = 9 ]
  then
    echo "Hi"
  fi
done
